### ISSUE TITLE
Update event meta data to have ApplicationID and AccountID

### ISSUE THREAD

**Issue by akeemphilbert** [wepala/weos#207]
This will help scope events

- [x] Add new meta data properties 
- [x] Remove module and group rom meta data 
- [x] Populate fields from context
